<?php
# This file was automatically generated by the MediaWiki 1.34.4
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "UT위키";
$wgMetaNamespace = "UT";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/md1_34_4";
$wgScriptExtension = ".php";
$wgArticlePath = "/r/$1";
$wgUsePathInfo = true;

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://utwiki.pe.kr";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "{$wgStylePath}/images/utlogo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = false; # UPO

$wgEmergencyContact = "apache@🌻.invalid";
$wgPasswordSender = "apache@🌻.invalid";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "utwiki";
$wgDBuser = "utwiki";
$wgDBpassword = "shp007312*";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgGenerateThumbnailOnParse = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgGroupPermissions['user']['upload'] = true;
$wgGroupPermissions['user']['reupload'] = true;
$wgGroupPermissions['user']['reupload-shared'] = true;
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp'];
$wgMaxUploadSize = '104857600';

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "ko";

$wgSecretKey = "2881ae241e155707aa68d20313cdd251ffec4c1c643776fec6d8b5fd06e11cda";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "1147066c7f07d7de";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "Liberty";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Liberty' );
wfLoadSkin( 'ModernSkylight' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'YouTube' );
wfLoadExtension( 'Widgets' );
wfLoadExtension( 'Popups' );
$wgPopupsReferencePreviewsBetaFeature = false; #1.34.4라 베타기능을 쓰지 못 하는 UT위키를 위해 주석 미리보기 기능을 정식으로 빼옴
$wgPopupsOptInDefaultState = 0; #미리보기 기능 기본으로 해제
$wgPopupsOptInStateForNewAccounts = 0; #미리보기 기능 기본으로 해제


# End of automatically generated settings.
# Add more configuration options below.
$wgExternalLinkTarget = '_blank'; #링크를 외부 창으로 여는 커맨드
$wgAllowExternalImages = true; #외부 이미지 보이게 하는 커맨드
$wgCapitalLinks = false; #문서제목 자동으로 대문자로 변하는거 방지
$wgRestrictDisplayTitle = false; #문서제목을 실제와 다르게 보여주는 것을 허용. 설레의 대부분 틀에 쓰임. true로 바꿔놓으면 죽일거임.
$wgGroupPermissions['sysop']['interwiki'] = true; #인터위키 수정용
$wgCiteResponsiveReferences = false; #각주가 여러 단으로 표시되는 것 방지

#위키쨩 스킨(모던 스카이라이트) 설정

#리브레 스킨 설정
$wgLibertyMainColor = "#1EDDFF"; #리브레 스킨 배경식
$wgLibertySecondColor = "#18B1CC"; #리브레 스킨 배경색 (마우스 올려뒀을 때 나타나는 색)
$wgLibertyMaxRecent = "15"; #최근변경 개수
$wgLibertyLiveRCArticleNamespaces = [NS_MAIN, NS_PROJECT, NS_TEMPLATE, NS_HELP, NS_CATEGORY, '3000']; #최근변경에 보여질 네임스페이스

#나무마크
require_once "$IP/extensions/php-namumark-mediawiki-master/namumark.php";
$wgRawHtml = true;
$wgAllowImageTag = true;
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_TEMPLATE] = true;
$wgAllowDisplayTitle = true;
$wgRestrictDisplayTitle = false;
$wgDefaultUserOptions['numberheadings'] = 1;

#하늘민국 네임스페이스
$wgExtraNamespaces['3000'] = "하늘민국";
$wgNamespacesToBeSearchedDefault['3000'] = true;
$wgExtraNamespaces['3001'] = "하늘민국토론";

# 사용자 권한 조정
# Edit
$wgGroupPermissions['user']['editsemiprotected'] = true;
$wgGroupPermissions['user']['upload_by_url'] = true;
# Management
$wgGroupPermissions['user']['bigdelete'] = true;
$wgGroupPermissions['user']['browsesearchive'] = true;
$wgGroupPermissions['user']['delete'] = true;
$wgGroupPermissions['user']['deletedhistory'] = true;
$wgGroupPermissions['user']['deletedtext'] = true;
$wgGroupPermissions['user']['mergehistory'] = true;
$wgGroupPermissions['user']['undelete'] = true;
# Administration
$wgGroupPermissions['user']['autopatrol'] = true;
$wgGroupPermissions['user']['import'] = true;
$wgGroupPermissions['user']['importupload'] = true;
$wgGroupPermissions['user']['unwatchedpages'] = true;
# Technical
$wgGroupPermissions['user']['apihighlimits'] = true;
$wgGroupPermissions['user']['autoconfirmed'] = true;
$wgGroupPermissions['user']['noratelimit'] = true;
$wgGroupPermissions['user']['override-export-depth'] = true;
$wgGroupPermissions['user']['suppressredirect'] = true;
# 확장기능
$wgGroupPermissions['user']['tboverride'] = true;
$wgGroupPermissions['user']['skipcaptcha'] = true;

# sysop 누락 권한 추가
# 인터페이스 관리자
$wgGroupPermissions['sysop']['editsitecss'] = true;
$wgGroupPermissions['sysop']['editsitejs'] = true;
$wgGroupPermissions['sysop']['editsitejson'] = true;
$wgGroupPermissions['sysop']['editusercss'] = true;
$wgGroupPermissions['sysop']['edituserjs'] = true;
$wgGroupPermissions['sysop']['edituserjson'] = true;
# 사무관
$wgGroupPermissions['sysop']['renameuser'] = true;
$wgGroupPermissions['sysop']['userrights'] = true;
# 기록보호자
$wgGroupPermissions['sysop']['deletelogentry'] = true;
$wgGroupPermissions['sysop']['deleterevision'] = true;
$wgGroupPermissions['sysop']['hideuser'] = true;
$wgGroupPermissions['sysop']['suppressionlog'] = true;
$wgGroupPermissions['sysop']['suppressrevision'] = true;
$wgGroupPermissions['sysop']['viewsuppressed'] = true;
# 이름공간
$wgGroupPermissions['sysop']['gadgets-edit'] = true;
$wgGroupPermissions['sysop']['gadgets-definition-edit'] = true;
# 사용자 가입 권한 유저단으로 설정
$wgGroupPermissions['user']['createaccount'] = true;

# 미가입자 권한 제거
$wgGroupPermissions['*']['oathauth-enable'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['editmyoptions'] = false;
$wgGroupPermissions['*']['editmyprivateinfo'] = false;
$wgGroupPermissions['*']['editmywatchlist'] = false;
$wgGroupPermissions['*']['viewmyprivateinfo'] = false;
$wgGroupPermissions['*']['viewmywatchlist'] = false;
$wgGroupPermissions['*']['writeapi'] = false;

# 가입자 권한 누락 추가
$wgGroupPermissions['user']['editmyoptions'] = true;
$wgGroupPermissions['user']['editmyprivateinfo'] = true;
$wgGroupPermissions['user']['editmywatchlist'] = true;
$wgGroupPermissions['user']['viewmyprivateinfo'] = true;
$wgGroupPermissions['user']['viewmywatchlist'] = true;

# 미가입자 보기권한 다시 허용
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['user']['read'] = true;

# 불필요한 그룹 제거
# 사무관
$wgGroupPermissions['bureaucrat']['renameuser'] = false;
unset( $wgGroupPermissions['bureaucrat'] );
unset( $wgRevokePermissions['bureaucrat'] );
unset( $wgAddGroups['bureaucrat'] );
unset( $wgRemoveGroups['bureaucrat'] );
unset( $wgGroupsAddToSelf['bureaucrat'] );
unset( $wgGroupsRemoveFromSelf['bureaucrat'] );
#자동 인증된 사용자
unset( $wgGroupPermissions['autoconfirmed'] );
unset( $wgRevokePermissions['autoconfirmed'] );
unset( $wgAddGroups['autoconfirmed'] );
unset( $wgRemoveGroups['autoconfirmed'] );
unset( $wgGroupsAddToSelf['autoconfirmed'] );
unset( $wgGroupsRemoveFromSelf['autoconfirmed'] );
# 인터페이스 관리자
unset( $wgGroupPermissions['interface-admin'] );
unset( $wgRevokePermissions['interface-admin'] );
unset( $wgAddGroups['interface-admin'] );
unset( $wgRemoveGroups['interface-admin'] );
unset( $wgGroupsAddToSelf['interface-admin'] );
unset( $wgGroupsRemoveFromSelf['interface-admin'] );
# 기록보호자
unset( $wgGroupPermissions['suppress'] );
unset( $wgRevokePermissions['suppress'] );
unset( $wgAddGroups['suppress'] );
unset( $wgRemoveGroups['suppress'] );
unset( $wgGroupsAddToSelf['suppress'] );
unset( $wgGroupsRemoveFromSelf['suppress'] );